---
title: "Project 2"
author: ""
date: "April 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)
```

```{r}
student.data <- readxl::read_excel('./data/StudentData.xlsx')
student.evaluation <- readxl::read_excel('./data/StudentEvaluation.xlsx')
```

- 4 values with missing response
- the rest of the missing data is small enough and spread out enough to impute

```{r}
missing.data.plot <- function(data){
  data %>%
    VIM::aggr(col=c('navyblue', 'yellow'),
      numbers=TRUE, sortVars=TRUE,
      labels=names(data), cex.axis=.7,
      gap=3, ylab=c('Missing Data', 'Pattern'), combined=TRUE
    )
}

missing.data.plot(student.data)
```

- eda suggests removing 4 training values with PH missing and 1 extreme outlier (remove total 5 rows)

```{r}
student.data <- student.data %>%
  filter(!is.na(student.data$PH),
         student.data$PH < 9)
```

- data prep pipeline

```{r}
clean.cols <- function(name){
  name <- gsub('\\s', '', name)
  name <- tolower(name)
  return(name)
}

pipeline <- function(data){
  ph <- data$PH
  
  data <- data %>%
    select(-PH) %>%
    mutate(`Brand Code` = as.factor(`Brand Code`)) %>%
    rename_all(list(f = ~clean.cols(.))) %>%
    mice::mice(m=5, maxit=10, seed=123, printFlag=FALSE) %>%
    mice::complete(1)
  
    x <- predict(dummyVars("~ .", data=data), newdata=data) %>%
        as_tibble()
  
  return(cbind(ph, x))
}

student.data.complete <- pipeline(student.data)
student.evaluation.complete <- pipeline(student.evaluation)
```

- verify all data imputed and present

```{r}
missing.data.plot(student.data.complete)
```

```{r}
missing.data.plot(student.evaluation.complete)
```

- write as csv for future use

```{r}
student.data.complete %>%
  write_csv('./data/student_data_complete.csv')

student.evaluation.complete %>%
  write_csv('./data/student_evaluation_complete.csv')
```

